import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Providers from "@/components/Providers";
import { CartWishlistProvider } from "@/components/Cart/CartWishlistContext";
import { Toaster } from "sonner";

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CartWishlistProvider>
              <Navbar />
              {children}
              <Toaster />
            </CartWishlistProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
